# Generated by Django 3.2.20 on 2023-08-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
